language: cpp
sudo: required
dist: trusty
osx_image: xcode7.3

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc

env:
  global:
  #encrypted HOMEBREW_GITHUB_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "qeD6xbuYNkYyAFx7LjVRh9341lKsticKVSbWt6irvhB304u83XkFq0CoA2xPwgTFXpn1ljAmApWbMQHb9SGTixVZ2WPlsMp5cWzSjDEBXPCjVEZ0uGH3p7/vyAzc/PGTg2WlRHzuvGc+8xN1JTZVjxXpUyTIArLodC0LhPkyu3cTAUvnVSa3r539hI3RBb8LSu8+k0NWIEM79QgTeqdX3xdBbOT4gz0BfH061Im/R++bWuIyyqviIXNoh8nRwUQfEG9rdYU5/Sxo4BT+wBe7yo9x7e+MYVFdz6CEJ7x4jLIp9JEHNXAsw4CssgmhXcEYfkY7RE4ZKYfJMqHuPfNFeWCxQ1++DsJplfRFEvqHlFhrqtyrR1Tc8aaMzbniFt3ZCiLgp+vKw2ENssEegiz8HhCxNmI9EdAamFgFRzmUh/BQwGUtqMalGesCIDJyk+qM3SgqQt0oPt5ptmoMfRei7M2jaurqNEP1dpBUUxbCOWrJ8xXVoY/NaPs6vcSEiFpuzdKNMY59gr9I/LhAp8r2J+Vv2lTcFzUrh5W8w3dxXi4P8R0KRkhQZPoGYekhSly6V5p1qAEfwq/qo7mG2P6p4C40VD85o2v/vlSKkH/CmIyU6YVwjaLETum+UNlpswtxz9eHUC2TCkunKCAZigUvzzWNHnadrhX8Q/ugYqM4JmA="
  - HOMEBREW_GITHUB_USERNAME=igagis

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    echo "deb https://dl.bintray.com/igagis/deb /" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq debhelper prorab doxygen libutki-dev libpapki-dev libunikod-dev;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    rvm use ruby-2.2.1 &&
    pod repo add --silent igagis https://$HOMEBREW_GITHUB_USERNAME:$HOMEBREW_GITHUB_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=ios &&
    
    brew tap igagis/tap &&
    brew update > /dev/null &&
    brew install prorab libutki libpapki libunikod;
  fi


script:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    make deb;
  fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    make &&
    make test &&

    xcodebuild -workspace ios/tests.xcworkspace -scheme tests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO &&

    if [ -n "$TRAVIS_TAG" ]; then prorab-deploy-cocoapods.sh igagis; else echo "Skip deploying to cocoapods because not a tagged commit!!!"; fi;
  fi

deploy:
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux && $CC = gcc
  file: travis_bintray.json
  user: igagis
  key:
    secure: "pATRl+8N1FyrQ7sIEUNdrvAZJCFim/b4pliEDCXRoa00odb7z35VTmDautJePnM9NceK40c6fpRrgSwCQ8lk7iZrmmnihw+58UV9Fqi1qyZQZ06DcZbljkV50R5ab67KaecscG+N+NqN2CsADd9C0IDdsvR0Qc4ACeD2qS+HOEJ3k85L7i+An0m4CefpZ9sDSDNcaOgLqqDHZBxUNr1OOcvw3NVQxvg/YIB6bIeUWML2RmHx/Qkp5MH7IvYpWy2osy/39x2qntzhNhhFzOGj69xdaTsMUAHLgSOFttVwtaKJTBuFQ5/F/3ZNw3K1pwjDgkSpsGlI/uzjxz3c203BHR5IB6OquO9osQcwWU4Rnvkz/KVZbiQlOJZV/Hq0R5JLRjiGy+qSIaAtmGNGfQNBnatwFUaYrWdEP6b7Pbqc3Fcb6oTLa7B5X+scCZYUyrLy6aWf7B9ukWuQrB97gJR/qol8rNGyYuHJyRRJfFGwxWH7iCxA58jgK7afofGgM+goGTR+OhzLB6E1KHcawQcz+wLidUGK5eMkYQ/Be2JvoZS2SOWDAff+M2tdzfZqqHQOtzkzIKOLKtWpj47rdEvgS9YjJxIChgvn7z0Kr5fgvUsOE9Z7bM6+tak+HwXCfhvPdwGopsRYomi5sQD8r68jVXNCAhYDO4teuPWyJYeZvAE="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: prorab-deploy-homebrew.sh igagis/tap
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx && $CC = clang
